### ISSUE TITLE
Add RHS T5000 to sniper rifle

### ISSUE THREAD

**Issue by StefArma** [StefArma/antistasiofficial#4]
For some reasons that rifle isn't classified as sniper rifle (probably RHS fault) 

\Functions\fn_SetupGearDB.sqf   might be tweaked to add "rhs_weap_t5000" to the gear_sniperRifles array

I've no clue on how to do it.

**Comment by DukeVenator** [comment]
Had a look into the code regarding how it grabs types atm it seems to be rhs's fault 
a way to fix it would be to make a hotfix mod that overrides the config data for the t5000 (not practical)
Might look into forcing a type change

**Comment by IrLED** [comment]
Why not to put the code like this into 
[fn_setupGearDB(]https://github.com/StefArma/antistasiofficial/blob/c5df0b81245f3f0ca9554b796e5f91f990ab9daf/Functions/fn_setupGearDB.sqf#L64)
```
_weaponType = _weapon select 1;
if(_name == "rhs_weap_t5000") then{_weaponType="SniperRifle"};
switch (_weaponType) do {
```
that will override RHS catigorization and push the weap to `gear_sniperRifles`

**Comment by StefArma** [comment]
Fantastic thanks!
