### ISSUE TITLE
Friendly Garrison AI

### ISSUE THREAD

**Issue by DukeVenator** [StefArma/antistasiofficial#9]
Need to buff garrison ai as they get wiped out way to easily by any chopper that decides to come by

**Comment by StefArma** [comment]
The whole AI need an improve.

**Comment by AlexTriada** [comment]
VCOM AI - the best!

**Comment by StefArma** [comment]
The last time i've seen VCOM in Antistasi was a mess, soldiers chasing helicopters into the water etc. Do you have a functioning version of VCOM? because integrating is a pain.

**Comment by DukeVenator** [comment]
The problem at the moment is the ai is so tightly controlled by antistasi its hard for vcom to do anything

**Comment by StefArma** [comment]
I mean ofcourse a version where what you say "controlled by antistasi" is replaced by "controlled by VCOM". We had that in 1.8 prototype but it wasn't good.

**Comment by AlexTriada** [comment]
VCOM is the best - 1.8 wasn’t good

**Comment by AlexTriada** [comment]
And VCOM may be connect as mod, so we need the AI: free to change AI mods, how you wanting
